/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TanstackFormRouteImport } from './routes/tanstack-form'
import { Route as ReactHookFormRouteImport } from './routes/react-hook-form'
import { Route as NumpadDemoRouteImport } from './routes/numpad-demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ControlsIndexRouteImport } from './routes/controls/index'

const TanstackFormRoute = TanstackFormRouteImport.update({
  id: '/tanstack-form',
  path: '/tanstack-form',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactHookFormRoute = ReactHookFormRouteImport.update({
  id: '/react-hook-form',
  path: '/react-hook-form',
  getParentRoute: () => rootRouteImport,
} as any)
const NumpadDemoRoute = NumpadDemoRouteImport.update({
  id: '/numpad-demo',
  path: '/numpad-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsIndexRoute = ControlsIndexRouteImport.update({
  id: '/controls/',
  path: '/controls/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/numpad-demo': typeof NumpadDemoRoute
  '/react-hook-form': typeof ReactHookFormRoute
  '/tanstack-form': typeof TanstackFormRoute
  '/controls': typeof ControlsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/numpad-demo': typeof NumpadDemoRoute
  '/react-hook-form': typeof ReactHookFormRoute
  '/tanstack-form': typeof TanstackFormRoute
  '/controls': typeof ControlsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/numpad-demo': typeof NumpadDemoRoute
  '/react-hook-form': typeof ReactHookFormRoute
  '/tanstack-form': typeof TanstackFormRoute
  '/controls/': typeof ControlsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/numpad-demo'
    | '/react-hook-form'
    | '/tanstack-form'
    | '/controls'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/numpad-demo' | '/react-hook-form' | '/tanstack-form' | '/controls'
  id:
    | '__root__'
    | '/'
    | '/numpad-demo'
    | '/react-hook-form'
    | '/tanstack-form'
    | '/controls/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NumpadDemoRoute: typeof NumpadDemoRoute
  ReactHookFormRoute: typeof ReactHookFormRoute
  TanstackFormRoute: typeof TanstackFormRoute
  ControlsIndexRoute: typeof ControlsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tanstack-form': {
      id: '/tanstack-form'
      path: '/tanstack-form'
      fullPath: '/tanstack-form'
      preLoaderRoute: typeof TanstackFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react-hook-form': {
      id: '/react-hook-form'
      path: '/react-hook-form'
      fullPath: '/react-hook-form'
      preLoaderRoute: typeof ReactHookFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numpad-demo': {
      id: '/numpad-demo'
      path: '/numpad-demo'
      fullPath: '/numpad-demo'
      preLoaderRoute: typeof NumpadDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls/': {
      id: '/controls/'
      path: '/controls'
      fullPath: '/controls'
      preLoaderRoute: typeof ControlsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NumpadDemoRoute: NumpadDemoRoute,
  ReactHookFormRoute: ReactHookFormRoute,
  TanstackFormRoute: TanstackFormRoute,
  ControlsIndexRoute: ControlsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
